### ISSUE TITLE
Error 404 on menu 'Fundamentals'

### ISSUE THREAD

**Issue by garstud** [ultraio/docs-blockchain#155]
### Steps to reproduce the issue
Go to https://developers.ultra.io
Click on the menu Tutorials > Fundamentals
(link: https://developers.ultra.io/tutorials/fundamentals/how-to-generate-a-keypair.html )

### Expected result
Acces to the documentation to create a Test/Dev account.

### Actual result
You will get a 404 error.
The menu link to **...keypair.html** instead of **...keypair** !)

And the direct link https://developers.ultra.io/tutorials/fundamentals/how-to-create-an-account.html no longer works
It now appears to have been replaced by https://developers.ultra.io/tutorials/fundamentals/tutorial-generate-key-and-create-testnet-account.html

**Comment by igor-sikachyna** [comment]
Fixed in https://github.com/ultraio/docs-blockchain/pull/170
