### ISSUE TITLE
The steps to interact with a smartcontract are incorrect!?

### ISSUE THREAD

**Issue by garstud** [ultraio/docs-blockchain#228]
### Steps to reproduce the issue
Go to https://developers.ultra.io/tutorials/smart-contracts/transact
Try to reproduce the steps on your smartcontract
The list of steps in the doc does not match those of the VScode v1.4.1 extension (the last).

### Expected result
Succeed to interact with the Smartcontract

### Actual result
Sometimes there is no message or information about the reason for the problem

### Recommendations
On the Doc, information is missing regarding the relationship between the doc and the program versions.
1. Clearly, the doc is not consistent with version 1.4.1 of the VScode extension "Ultra.io Smart Contract Toolkit"
2. you must add **versioning as a prerequisite** to the doc, for example: 
"_This doc is compatible with the VScode v1.3.3 extension_"
(and therefore not the latest 1.4.1! This would limit misunderstandings)
3. try to keep the **doc up to date when you deliver a new version** of the extension. Clearly the steps in the tutorial are quite well done but they do not correspond with what the extension displays

and others for the **Smartcontract extensions v1.4.1** in the Discord dev-doc-feedbacks:
https://discord.com/channels/431591787321098270/1179412779883573330/1257638536379764746

**Comment by igor-sikachyna** [comment]
Resolved in: https://github.com/ultraio/docs-blockchain/pull/234 and https://github.com/ultraio/ultra-cpp-extension/pull/26
